# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: cccc

before:
  hooks:
    - go mod tidy

builds:
  - id: cccc
    main: ./cmd/ccc
    binary: cccc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: mkoepf
    name: clean-claude-code-config
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"

brews:
  - repository:
      owner: mkoepf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: "https://github.com/mkoepf/clean-claude-code-config"
    description: "CLI tool for cleaning up Claude Code configuration"
    license: "MIT"
    install: |
      bin.install "cccc"
    test: |
      system "#{bin}/cccc", "--help"
